### ISSUE TITLE
Python implementation of solving_schrodinger's equation

### ISSUE THREAD

**Issue by YaBoi20035** [princezako/boxing-a-cat#2]
At the end of section 4 the task is to recreate the code such that it works for any input of potential. We need to do this and then have it all defined as easy to use functions

**Comment by princezako** [comment]
do we do this using the terminal

**Comment by YaBoi20035** [comment]
So far I'm just writing a function to deal with the second derivative in the hamiltonian. After that, I plan on writing a function defining the hamiltonian generally

**Comment by YaBoi20035** [comment]
I'm currently defining a class that creates an environment for the system to run in. This will allow for easy modification of the potential of this environment using the python exec command. For people in the testing part of the project, you'll need to make various tests and errors surrounding this command because I'm sure people will have difficulty running it correctly. Once I have finished this I'll add some premade options for ease of creation of a potential.

I've also noticed that the upper and lower x-boundaries act as infinite potential as the wavefunction is always zero there so there is no need for a potential well preset.

**Comment by ElizabethBonnett** [comment]
That all sounds brilliant. Let us know when you need to pull anything

**Comment by princezako** [comment]
What can I do to help?

**Comment by YaBoi20035** [comment]
okay, so far I've been writing the bit of the code that allows us to customise the potential. I've written what I think to be some pretty good code that allows us to input a function of x and have the potential be whatever that results in ("x**2" results in an x squared graph of potential like in part 4 of the lab notebook). What remains to be done is the actual code that solves the wavefunction. I haven't touched that because it's basically just the code provided to us. You could do that but you'll have to be careful because you'll need to ensure that it can be integrated into the class I made or utilise that class to produce a result. I'll try and push it today so you can see and interact with my code.

**Comment by princezako** [comment]
Okay sure, I can give that a go. I’m guessing it’ll notify us when someone pushes something through but if not then let me know when.

**Comment by princezako** [comment]
So looking at the code you pushed, you've defined x, t and potential with self.x_array, self.y_array and self.potential so I should use these in my code going forward

**Comment by princezako** [comment]
I'm looking into adding a progress bar. Seems a bit complicated but why not try

**Comment by YaBoi20035** [comment]
remember: write to csv file

**Comment by YaBoi20035** [comment]
to do: write a help function that prints list of commands

**Comment by princezako** [comment]
I'll give the write to csv file thing a go
