### ISSUE TITLE
Making tests

### ISSUE THREAD

**Issue by ElizabethBonnett** [princezako/boxing-a-cat#5]

**Comment by princezako** [comment]
example test: see if number input only accepts numbers

**Comment by ciarancromwell** [comment]
lets have a quick run through of the notebook about testing, just to get a better understanding

**Comment by ElizabethBonnett** [comment]
We (Yana, Elizabeth, Ciaran) are working on the tests on Yana's laptop together. This means most pull requests will come from her laptop but we have all been working on the code together.

**Comment by YaBoi20035** [comment]
one test we're gonna need is to make sure that the solving_schrodinger equation is called before the function that makes the gif

**Comment by yanakushlova** [comment]
Eliazbeth, could you help me do a pull request so that we can check what we have done so far on testing and checking?

**Comment by ciarancromwell** [comment]
i have got the test to verify that it works, provided an x variable is given, just trying to make sure it gives a readable error when the user input is not a string.

**Comment by princezako** [comment]
nice progress :) you love to see it
