### ISSUE TITLE
Research on how to setup package to it can be installed

### ISSUE THREAD

**Issue by ElizabethBonnett** [princezako/boxing-a-cat#6]

**Comment by ElizabethBonnett** [comment]
So far I’ve read through the information we were given on installing the package. Today or tomorrow I’ll install a test package to make sure I know how to do this with our real project once we’ve finished it.

**Comment by princezako** [comment]
Sounds good

**Comment by ElizabethBonnett** [comment]
I've had some trouble with the testing of the upload so I have had to start again with a new package. I will let you all know once I have got it to work

**Comment by princezako** [comment]
okay cool

**Comment by ElizabethBonnett** [comment]
I’ve spent all of labs trying to work out how to do this today. I’m on the last step but I’m getting an error so I’ll stop for today and try again over the weekend.

**Comment by ElizabethBonnett** [comment]
Please can everyone let me know when the package is finished so I can upload it as I could take a bit of time

**Comment by ElizabethBonnett** [comment]
I've made a new package so I will retry uploading it onto test PYPI. I'll let you all know how its going.

**Comment by ElizabethBonnett** [comment]
I got it to work!!!

We can now make a link that takes you to a test pypi page which tells you how to install the package through a link (https://test.pypi.org/project/example-package-elizabethb/0.0.1/ - for the example one). 

We can add this to the README so people know how to access the information
